version: '3'
services:
  crawler:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SQS_QUEUE_URL=https://sqs.us-east-1.amazonaws.com/267074127319/test
    image: crawler:latest

