awsRegion: "${awsRegion}"
cloudProvider: aws
autoDiscovery:
  enabled: true
fullnameOverride: "cluster-autoscaler"
deployment:
  annotations:
    eks.amazonaws.com/role-arn: "${roleArn}"
rbac:
  create: true
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "${roleArn}"
# nodeSelector:
#   eks.amazonaws.com/capacityType: ON_DEMAND