apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-app
  namespace: sample-apps
  labels:
    app: api-app
spec:
  selector:
    matchLabels:
      app: api-app
  replicas: 1
  template:
    metadata:
      labels:
        app: api-app
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      containers:
      - name: api-container
        image: {{ .Values.dockerImageUrl }}
        imagePullPolicy: Always
        env:
          - name: SQS_QUEUE_URL
            value: {{ .Values.sqsQueueUrl }}
          - name: AWS_DEFAULT_REGION
            value: {{ .Values.region }}
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
