apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler-app
  namespace: sample-apps
  labels:
    app: crawler-app
spec:
  selector:
    matchLabels:
      app: crawler-app
  replicas: 1
  template:
    metadata:
      labels:
        app: crawler-app
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      containers:
      - name: crawler-container
        image: {{ .Values.dockerImageUrl }}
        imagePullPolicy: Always
        env:
          - name: SQS_QUEUE_URL
            value: {{ .Values.sqsQueueUrl }}
          - name: AWS_DEFAULT_REGION
            value: {{ .Values.region }}
          - name: S3_BUCKET
            value: {{ .Values.s3Bucket }}
        resources:
          limits:
            memory: "1000Mi"
            cpu: "1000m"
