apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler-app
  namespace: sample-apps
  labels:
    app: crawler-app
spec:
  selector:
    matchLabels:
      app: crawler-app
  replicas: 1
  template:
    metadata:
      labels:
        app: crawler-app
    spec:
      containers:
      - name: crawler-container
        image: docker.io/llleonardo/jb-assignment-crawler:latest
        resources:
          limits:
            memory: "1000Mi"
            cpu: "1000m"

            project: default
source:
  repoURL: 'https://github.com/leonardollobato/jb-assignment'
  path: argocd/applications/blue-green
  targetRevision: main
destination:
  server: 'https://kubernetes.default.svc'
  namespace: sample-apps
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
