apiVersion: v1
kind: Service
metadata:
  namespace: sample-apps
  name: crawler-svc
  labels:
    app: crawler-app
spec:
  type: NodePort
  selector:
    app: crawler-app
  ports:
    - port: 80
      targetPort: 80